### ISSUE TITLE
Regex Error 

### ISSUE THREAD

**Issue by Subegya** [Herald-Engineers/WaveBilling-FrontEnd#8]
The contact us field should be filled with exactly 10 numbers but it allows the input to be greater than 10 numbers.

**Comment by maharjanshreya** [comment]
![Screenshot (90)](https://user-images.githubusercontent.com/127919986/229327422-d74436a1-a891-4815-b27e-6000b73502ca.png)

I forgot to put the error message in the function and now this issue has been solved
